name: Stylua Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  stylua-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Stylua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip -d /usr/local/bin
          chmod +x /usr/local/bin/stylua

      - name: Run Stylua check
        run: stylua --check .
